---
# tasks file for setup-repo
- name: Ensure directory for mounting media exists
  file: "/mnt/{{ distro }}"
  state: directory

- name: Ensure installation media is mounted
  mount:
    path: "/mnt/{{ distro }}"
    src: /dev/cdrom
    fstype: iso9660
    opts: ro,noauto
    state: mounted

- name: Validate installation media
  stat:
    path: "{{ repo_file }}"
  register: stat_result
  failed_when: stat_result is undefined

- name: Ensure repo dir exists
  file:
    path: "{{ repo_base_dir }}/{{ distro }}"
    state: directory

- name: Copy installation media to webdir
  copy:
    src: "/mnt/{{ distro }}/"
    dest: "{{ repo_base_dir }}/{{ distro }}"
