---
# tasks file for setup-repo
- name: Ensure installation media is mounted
  mount:
    path: /mnt/redhat
    src: /dev/cdrom
    fstype: iso9660
    opts: ro,noauto
    state: mounted

- name: Validate installation media
  stat:
    path: "{{ repo_file }}"
  register: stat_result
  failed_when: stat_result is undefined

- name: Ensure mount dir exists
  file:
    path: /mnt/redhat
    state: directory
    
- name: Ensure repo dir exists
  file:
    path: "{{ repo_base_dir }}/{{ distro }}"
    state: directory

- name: Copy installation media to webdir
  synchronize:
    src: /mnt/redhat/
    dest: "{{ repo_base_dir }}/{{ distro }}"
