---
- name: Install and configure DNS
  hosts: localhost
  become: true
  vars_files: 
    - vars/repo-config.yml
    - vars/network-config.yml
    - vars/inventory.yml

  roles:
  - install-configure-dns
  - install-configure-http
  - install-configure-tftp
  - install-configure-dhcp
#  - setup-repo
  - configure-pxe-server
  - regenerate-kickstart


