---
- name: Install and configure DNS
  hosts: localhost
  become: true
  vars_files: 
    - vars/repo-config.yml
    - vars/network-config.yml
    - vars/inventory.yml

  roles:
  - regenerate-kickstart


