---
# tasks file for tftp-server
- name: Ensure tftp-server and firewalld are installed
  yum:
    name: 
      - tftp-server
      - firewalld
    state: present

- name: Ensure firewalld is enabled and started
  service:
    name: firewalld
    state: started
    enabled: true

- name: Ensure tftp.socket is enabled and started
  systemd:
    name: tftp.socket
    state: started
    enabled: true

- name: Ensure tftp service is enabled on firewall
  firewalld:
    service: tftp
    permanent: yes
    state: enabled
    immediate: true
