---
# tasks file for regenerate-kickstart
- name: Checking {{ repo_file }} exists
  stat:
    path: "{{ repo_file }}"
  register: stat_result
  failed_when: stat_result is undefined

- name: Set distro name
  set_fact:
    distro_full_name: "{{ lookup('ini', 'name section=InstallMedia file={{ repo_file }}') }}"
 
- name: Ensure kickstart dir exists
  file:
    path: "{{ kickstart_dir }}"
    state: directory

- name: Render kickstart.cfg
  template:
    src: ks.j2
    dest: "{{ kickstart_dir }}/{{ item.name }}.ks.cfg"
  loop: "{{ ansible_nodes }}"

- name: Ensure directory for post install setup is present
  file:
    path: "{{ post_setup_dir }}"
    state: directory

- name: Copy authorized_key to for kickstart
  copy:
    content: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}
    dest: "{{ post_setup_dir }}/authorized_keys"
    mode: 0644
    owner: root
    group: root
    
