---
- name: Get distro version from media
  hosts: localhost
  gather_facts: false
  vars:
    mount_point: /mnt/install-repo
    file_name: "{{ mount_point }}/media.repo"

  tasks:
  
  - name: Checking {{ file_name }} exists
    stat:
      path: "{{ file_name }}"
    register: stat_result
    failed_when: stat_result is undefined

  - name: Set distro name
    set_fact:
      distro_full_name: "{{ lookup('ini', 'name section=InstallMedia file={{ file_name }}') }}"

  - name: set distro short name
    set_fact:
      distro: "centos"
    when: distro_full_name is search 'CentOS'

  - name: Print distro
    debug:
      msg: "{{ distro }}"
