---
- name: find files and print results
  gather_facts: false
  hosts: localhost

  tasks:

  - name: find shimloader in /var/www
    find:
      paths: /var/www/html/install-repo
      patterns:
        - "shim-x64*.rpm"
        - "grub2-efi-x64*.rpm"
      recurse: yes
      excludes: 
        - "*cdboot*"
        - "*modules*"
    register: shimloader_rpms

  - name: Ensure temp location for extraction exists
    file:
      dest: /tmp/test
      state: directory
      owner: root
      group: root
      mode: 0775
    when: shimloader_rpms is defined

  - name: Extract rpms
    shell: "rpm2cpio {{ item.path }} | cpio -dimv"
    args:
      chdir: /tmp/test
    loop: "{{ shimloader_rpms.files }}"

  - name: Set permissions on temp folder
    file:
      dest: "{{ item }}"
      state: directory
      recurse: true
      owner: root
      group: root
      mode: 0775
    loop:
      - "/tmp/test"
      - "/tmp/efi-test/uefi/centos"
      - "/tmp/efi-test/uefi/redhat"
  
  - name: Find redhat EFI files
    find: 
      path: /tmp/test/boot/efi/EFI/redhat
      patterns: "*.efi"
    register: redhat_efi_files

  - name: Find centos EFI files
    find:
      path: /tmp/test/boot/efi/EFI/centos
      patterns: "*.efi"
    register: centos_efi_files

  - name: Print results redhat
    debug:
      msg: "{{ item.path }}"
    loop: "{{ redhat_efi_files.files }}"

  - name: Copy redhat EFI files
    copy:
      src: "{{ item.path }}"
      dest: /tmp/efi-test/uefi/redhat
    loop: "{{ redhat_efi_files.files }}"
    when: redhat_efi_files is defined

  - name: Print results for centos
    debug:
      msg: "{{ item.path }}"
    loop: "{{ centos_efi_files.files }}"

  - name: Copy centos EFI files
    copy:
      src: "{{ item.path }}"
      dest: /tmp/efi-test/uefi/centos
    loop: "{{ centos_efi_files.files }}"
    when: centos_efi_files is defined
